### PR TITLE
fix for 7.2, go install in tmp causes problems and accounts needed to…

### PR DESCRIPTION
**Pull request by vesche**
Two changes for installing on RHEL/CentOS 7.2

### CODE REVIEW

**Comment by vesche** [comment]
I signed it!

**Comment by gconnell** [comment]
I'm surprised toat either of these things (install in /tmp, need accounts before building) is an issue.  Could you drop me the error messages you're seeing for either of these?

I'm somewhat concerned about installing outside of /tmp, the other change seems totally fine.  Would $(mktemp -d) be better than using /tmp directly?

**Comment by vesche** [comment]
```
Installing golang ...
Building/Installing stenographer
warning: "./..." matched no packages
can't load package: package .: no buildable Go source files in /tmp
can't load package: package .: no buildable Go source files in /tmp
cp: cannot stat ‘stenographer’: No such file or directory
chown: invalid user: ‘stenographer:root’
chmod: cannot access ‘/usr/bin/stenographer’: No such file or directory
Building/Installing stenotype
~/stenographer/stenotype ~/stenographer
g++ -std=c++0x -g -Wall -fno-strict-aliasing  -rdynamic -O2 -fPIC -fPIE -pie -fstack-protector -D_FORTIFY_SOURCE=2 -c -o util_gcc.o util.cc
g++ -std=c++0x -g -Wall -fno-strict-aliasing  -rdynamic -O2 -fPIC -fPIE -pie -fstack-protector -D_FORTIFY_SOURCE=2 -c -o packets_gcc.o packets.cc
g++ -std=c++0x -g -Wall -fno-strict-aliasing  -rdynamic -O2 -fPIC -fPIE -pie -fstack-protector -D_FORTIFY_SOURCE=2 -c -o index_gcc.o index.cc
g++ -std=c++0x -g -Wall -fno-strict-aliasing  -rdynamic -O2 -fPIC -fPIE -pie -fstack-protector -D_FORTIFY_SOURCE=2 -c -o aio_gcc.o aio.cc
g++ -std=c++0x -g -Wall -fno-strict-aliasing  -rdynamic -O2 -fPIC -fPIE -pie -fstack-protector -D_FORTIFY_SOURCE=2 -c -o stenotype_gcc.o stenotype.cc
g++ -std=c++0x -g -Wall -fno-strict-aliasing  -rdynamic -O2 -fPIC -fPIE -pie -fstack-protector -D_FORTIFY_SOURCE=2 -o stenotype util_gcc.o packets_gcc.o index_gcc.o aio_gcc.o stenotype_gcc.o -lleveldb -lrt -laio -lpthread -lsnappy -lseccomp -Wl,-z,now -Wl,-z,relro
~/stenographer
‘stenotype/stenotype’ -> ‘/usr/bin/stenotype’
chown: invalid user: ‘stenographer:root’

```

Here's a snip of the output where the errors are produced (without my changes). Doing `cd /tmp` persists outside of `install_golang ()`, and causes `build_stenographer ()` to hiccup on the `go get` and `go build`. A better fix may be just adding absolute paths for installing golang in tmp, but a quick fix was just to have the go tarball be downloaded in the working directory.

The invalid user errors are produced because the script builds stenographer and stenotype (which involves changing some file permissions for the stenographer user) before the stenographer user was created. So, I moved up `add_accounts` to come before building stenographer and stenotype to fix these issues.

**Comment by gconnell** [comment]
To not mess up folks' working dirs, can we do this for directories:

```shell
TMP="$(mktemp -d)"
pushd $TMP
blah blah stuff in tmp
popd
```

or, alternatively, use absolute path ${TMP}/xxx everywhere.

I'm totally fine with the accounts stuff.

**Comment by vesche** [comment]
Sounds good, tested and working. I pushed another commit.

**Comment by gconnell** [comment]
Thanks!

**Pull request merged**
