### PR TITLE
fix bugs related to introduction of flag --blocksize_kb

### PR DESCRIPTION
**Pull request by emillynge**
Dear maintainers

Please accept this PR which fixes a couple of issues that has arisen due to the introduction of --blocksize_kb option.

In general these issue stem from the previous assumption that a block is 1MB.

The stats MBps and MB are wrong when bz!=1MB
Files are not rotated at the right time. Specifically, bz>1MB can lead to a PKT file larger than 4Gb which causes a fatal error.
To fix the issue, i've introduced a new variable blocks_per_file which is determined by the values flag_filesize_mband flag_blocksize_kb.

I'm not entirely sure whether the pattern of calculating blocks_per_file in the switch block is the right way to go.

NB: closed previous PR in order to create PR from company repo instead

### CODE REVIEW

**Comment by emillynge** [comment]
@googlebot I signed it!

**Comment by wehowsky-admin** [comment]
@googlebot I signed it!

**Comment by emillynge** [comment]
@googlebot I signed it!

**Comment by emillynge** [comment]
@googlebot I signed it!

**Comment by gconnell** [comment]
Thanks, and sorry for the late reply!

**Pull request merged**
